baseurl: "/temp_blog"
url: "https://dion-m-sato.github.io"
github: [metadata]
remote_theme: thelehhman/texture
texture:
  title: TEMPORARY
  tagline: movie, novel
  date_format: "%b %-d, %Y"
  style: red
  showNav: true

plugins:
  - jekyll-feed #何かは不明
  - jekyll-remote-theme
  - github-pages
