baseurl: "/temp_blog"
url: "https://dion-m-sato.github.io"
remote_theme: thelehhman/texture
texture:
  title: TEMPORARY
  tagline: movie, novel
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  
