baseurl: "/temp_blog"
url: "https://dion-m-sato.github.io"
github: [metadata]
plugins:
  - jekyll-feed #feedback_information
  - jekyll-remote-theme
  - github-pages
    
remote_theme: thelehhman/texture
texture:
  title: TEMPORARY
  tagline: movie, novel
  date_format: "%b %-d, %Y"
  style: red
  showNav: true
  analytics_id: 'UA-155140951-1'
